version: '3.8'

services:
  task-manager-eureka:
    build: ../Task-Manager-Eureka
    container_name: task-manager-eureka
    ports:
      - "8761:8761"  #hostport:containerport
    networks:
      - task-network

  task-manager-gateway:
    build: ../Task-Manager-Gateway
    container_name: task-manager-gateway
    ports:
      - "8080:8080"
    depends_on:
      - task-manager-eureka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - task-network

  task-manager:
    build: ../Task-Manager-Springboot
    container_name: task-manager
    ports:
      - "8081:8081"  # Updated to match app's actual port
    depends_on:
      - task-manager-eureka
      - task-manager-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-manager-postgres:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=taskuser
      - SPRING_DATASOURCE_PASSWORD=taskpass
    networks:
      - task-network

  task-manager-postgres:
    image: postgres:15
    container_name: task-manager-postgres
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - task-manager-postgres
    networks:
      - task-network

  task-manager-frontend:
    build: ../task-manager-frontend-master
    container_name: task-manager-frontend
    ports:
      - "3000:3000"
    depends_on:
      - task-manager-gateway
    environment:
      - NODE_ENV=production
    networks:
      - task-network


networks:
  task-network:
    driver: bridge

volumes:
  postgres_data: