apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      imagePullSecrets:
          - name: ghcr-creds
      containers:
        - name: task-manager
          image: ghcr.io/saleos-sam/task-manager:v1.0.0-dev
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker