apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: task-manager
spec:
  selector:
    app: task-manager
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
