apiVersion: v1
kind: Service
metadata:
  name: task-manager-frontend
  namespace: task-manager
spec:
  selector:
    app: task-manager-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer