apiVersion: v1
kind: Service
metadata:
  name: task-manager-eureka
  namespace: task-manager
spec:
  selector:
    app: task-manager-eureka
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
