apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: task-manager-postgres
  namespace: task-manager
  labels:
    app: task-manager-postgres
spec:
  serviceName: task-manager-postgres
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-postgres
  template:
    metadata:
      labels:
        app: task-manager-postgres
    spec:
      # Node affinity to schedule on userpool nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/agentpool
                operator: In
                values:
                - userpool
      # Tolerations for userpool node taints
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "high-performance"
        effect: "NoSchedule"
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: taskdb
            - name: POSTGRES_USER
              value: taskuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U taskuser -d taskdb
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U taskuser -d taskdb
            initialDelaySeconds: 60
            periodSeconds: 30
  # StatefulSet manages its own PVCs
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: task-manager
type: Opaque
data:
  postgres-password: dGFza3Bhc3M=  # base64 encoded "taskpass"
