apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-frontend
  namespace: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-frontend
  template:
    metadata:
      labels:
        app: task-manager-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      # Node affinity to schedule on userpool nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/agentpool
                operator: In
                values:
                - userpool
      # Tolerations for userpool node taints
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "high-performance"
        effect: "NoSchedule"
      containers:
        - name: task-manager-frontend
          image: ghcr.io/saleos-sam/task-manager-frontend:v1.0.0-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # Resource limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Readiness probe to ensure app is ready
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Liveness probe to restart if unhealthy
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
