apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-gateway
  namespace: task-manager
  labels:
    app: task-manager-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-gateway
  template:
    metadata:
      labels:
        app: task-manager-gateway
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      # Node affinity to schedule on userpool nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/agentpool
                operator: In
                values:
                - userpool
      # Tolerations for userpool node taints
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "high-performance"
        effect: "NoSchedule"
      containers:
        - name: task-manager-gateway
          image: ghcr.io/saleos-sam/task-manager-gateway:v1.0.0-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
